[package]
name = "muchat"
version = "0.0.1"
edition = "2021"
license = "MIT"

[dependencies]
iced = { version = "0.13.1", features = ["markdown", "highlighter", "debug"] }
libc = "0.2.161"
open = "5.3.0"
thiserror = "1.0.64"
